# Generated by Django 4.1.4 on 2022-12-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='user_id',
        ),
    ]
