# Generated by Django 4.1.4 on 2022-12-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_user_account_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
    ]
