# Generated by Django 4.1.4 on 2022-12-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_rename_user_id_account_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='debit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.FloatField(default=0),
        ),
    ]
