# Generated by Django 4.1.4 on 2022-12-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_user_account_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='account',
            new_name='account_id',
        ),
    ]
