# Generated by Django 4.1.4 on 2022-12-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_account_account_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_id',
            new_name='user',
        ),
    ]
